---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fen
  namespace: hpc
spec:
  selector:
    matchLabels:
      app: fen
  serviceName: fen
  replicas: 1
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: fen
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: fen
          image: joshuagad/fen:24.05.2
          imagePullPolicy: Always
          #livenessProbe:
          #  successThreshold: 1
          #  failureThreshold: 3
          #  tcpSocket:
          #    port: ssh
          #readinessProbe:
          #  successThreshold: 1
          #  failureThreshold: 3
          #  tcpSocket:
          #    port: ssh
          securityContext:
            privileged: true
          ports:
          - containerPort: 22
            name: ssh
          volumeMounts:
          - mountPath: /home/users
            name: home-users
          - mountPath: /home/projects
            name: home-projects
      volumes:
      - name: home-users
        nfs:
          server: 10.199.11.144
          path: /volume1/polab-users
      - name: home-projects
        nfs:
          server: 10.199.11.144
          path: /volume1/polab-projects

---
apiVersion: v1
kind: Service
metadata:
  name: fen
  namespace: hpc
  labels:
    app: fen
spec:
  type: ClusterIP
  selector:
    app: fen
  ports:
    - name: ssh
      port: 22

