---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fen
  namespace: hpc
spec:
  selector:
    matchLabels:
      app: fen
  serviceName: fen
  replicas: 1
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: fen
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: home-users
        nfs:
          server: 172.16.42.10
          path: /users
      - name: home-projects
        nfs:
          server: 172.16.42.10
          path: /projects
      - name: etc-sssd
        emptyDir: {}
      - name: cm-etc-sssd
        configMap:
          name: sssd-conf
          defaultMode: 0600
      - name: etc-sysconfig
        configMap:
          name: etc-sysconfig
          defaultMode: 0644
      - name: slurm-key
        configMap:
          name: slurm-key
          defaultMode: 0600
      initContainers:
        - name: sssd-prep
          image: joshuagad/fen:24.05.2
          volumeMounts:
            - mountPath: /etc/sssd
              name: etc-sssd
            - mountPath: /tmp/sssd
              name: cm-etc-sssd
          command:
            - sh
            - -c
            - install -o sssd -m 0600 /tmp/sssd/sssd.conf /etc/sssd
      containers:
        - name: fen
          image: joshuagad/fen:24.05.2
          imagePullPolicy: Always
          #livenessProbe:
          #  successThreshold: 1
          #  failureThreshold: 3
          #  tcpSocket:
          #    port: ssh
          #readinessProbe:
          #  successThreshold: 1
          #  failureThreshold: 3
          #  tcpSocket:
          #    port: ssh
          securityContext:
            privileged: true
          ports:
          - containerPort: 22
            name: ssh
          volumeMounts:
          - mountPath: /home/users
            name: home-users
          - mountPath: /home/projects
            name: home-projects
          - mountPath: /etc/sssd
            name: etc-sssd
          - mountPath: /etc/sysconfig/sackd
            name: etc-sysconfig
            subPath: sackd
          - mountPath: /etc/slurm/slurm.key
            name: slurm-key
            subPath: slurm.key
---
apiVersion: v1
kind: Service
metadata:
  name: fen
  namespace: hpc
  labels:
    app: fen
spec:
  type: ClusterIP
  selector:
    app: fen
  ports:
    - name: ssh
      port: 22

